abstract: infest your objects with hives
author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Mixin-ExtraFields-Hive
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Hive: 0
  Mixin::ExtraFields: 0.002
version: 0.001
