--- 
abstract: infest your objects with hives
author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Mixin-ExtraFields-Hive
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Hive: 0.05
  Mixin::ExtraFields: 0.002
  perl: 5.6.0
version: 0.003
